# Generated by Django 4.2.23 on 2025-11-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_alter_reminder_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
