# Generated by Django 4.2.23 on 2025-11-11 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0004_reminder_user_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
