# Generated by Django 4.2.23 on 2025-11-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0005_remove_reminder_user_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
